### ISSUE TITLE
Create resolvers to easily get the entities in controllers

### ISSUE THREAD

**Issue by EspenK** [EspenK/repost-spring#29]
- [ ] Resub resolver
- [ ] Post resolver
- [ ] Comment resolver
- [ ] User resolver
- [x] CurrentUser resolver

**Comment by pckv** [comment]
CurrentUser resolver was implemented in #31. The rest seem unnecessarily difficult to implement with OpenAPI, so we decided against it. The issues with OpenAPI were mostly springdoc-openapi requiring custom parameters for tweaking the expected results.

Instead it was easy enough to have a `get` method in the respective service and use that on the ID.
